-- 1. Create a new table for storing Biometric/Passkey credentials
-- We use TEXT for credential_id and public_key to easily store Base64URL strings
-- This connects to the existing 'users' table via user_id

CREATE TABLE IF NOT EXISTS authenticators (
    credential_id TEXT PRIMARY KEY,                 -- The unique ID for this passkey
    credential_public_key TEXT NOT NULL,            -- The public key generated by the device
    counter BIGINT DEFAULT 0 NOT NULL,              -- To prevent replay attacks
    credential_device_type VARCHAR(255) NOT NULL,   -- e.g., 'single_device' or 'multi_device'
    credential_backed_up BOOLEAN DEFAULT FALSE,     -- Whether it's synced (e.g., iCloud Keychain)
    transports VARCHAR(255),                        -- e.g., 'internal', 'usb', 'nfc'
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP
);

-- 2. (Optional) Index for faster lookups by user
CREATE INDEX IF NOT EXISTS idx_authenticators_user_id ON authenticators(user_id);
