-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users & Roles
-- Roles: 'admin', 'faculty', 'student'
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) CHECK (role IN ('admin', 'faculty', 'student')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Faculty Profile
CREATE TABLE faculty (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    designation VARCHAR(100),
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Students Profile
CREATE TABLE students (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    enrollment_no VARCHAR(50) UNIQUE NOT NULL,
    erp_id VARCHAR(50) UNIQUE NOT NULL, -- Added ERP ID
    course_year VARCHAR(20) DEFAULT 'BCA VI',
    section VARCHAR(10) DEFAULT 'Morning',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Subjects
CREATE TABLE subjects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    credits INT DEFAULT 3,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Classes / Sections (To manage different batches)
CREATE TABLE classes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(50) NOT NULL, -- e.g., 'BCA VI'
    section VARCHAR(50) NOT NULL, -- e.g., 'Morning'
    UNIQUE(name, section)
);

-- 6. Timetable
-- Links a Class, Subject, Faculty, and Time Slot
CREATE TABLE timetable (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
    subject_id UUID REFERENCES subjects(id) ON DELETE CASCADE,
    faculty_id UUID REFERENCES faculty(id) ON DELETE SET NULL,
    day_of_week VARCHAR(10) CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_no VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Attendance Sessions (Generated by Faculty/Admin for a specific class slot)
CREATE TABLE attendance_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    timetable_id UUID REFERENCES timetable(id) ON DELETE CASCADE,
    faculty_id UUID REFERENCES faculty(id) ON DELETE CASCADE, -- Who started the session
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NOT NULL, -- Session expiry time
    qr_code VARCHAR(255) NOT NULL, -- Dynamic QR content/hash
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. Attendance Records (Individual student attendance)
CREATE TABLE attendance_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES attendance_sessions(id) ON DELETE CASCADE,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    status VARCHAR(20) CHECK (status IN ('Present', 'Absent', 'Late')) DEFAULT 'Present',
    marked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    device_info VARCHAR(255), -- Optional: to prevent proxy
    location_lat DECIMAL(9,6), -- Optional: Geo-fencing
    location_long DECIMAL(9,6),
    UNIQUE(session_id, student_id) -- Prevent duplicate attendance
);

-- SEED DATA -------------------------------------------------------------

-- 1. Insert Class
INSERT INTO classes (name, section) VALUES ('BCA VI', 'Morning');

-- 2. Insert Subjects (Based on Table)
INSERT INTO subjects (code, name, credits) VALUES 
('MKC', 'Data Warehousing and Data Mining', 3),
('NPN', 'Web Programming', 3),
('RD', 'Software Project Management', 3),
('RCH', 'R Programming', 3), -- Assuming RCH is code for R Prog
('Lab-WP', 'Lab on Web Programming', 2),
('Lab-DV', 'Lab on Data Visualization', 2),
('DM', 'Digital Marketing', 2),
('IC', 'Indian Culture', 2);

-- 3. Insert Faculty (Placeholders)
-- We need to create Users first, then Faculty. 
-- Using Common Table Expressions (CTE) or DO blocks for dynamic inserts is better, 
-- but for raw SQL script simplify with assumption or direct inserts if IDs were static.
-- Here we'll just insert users and assume we can link them.

-- Admin User
INSERT INTO users (email, password_hash, full_name, role) 
VALUES ('admin@college.edu', 'hashed_secret', 'Admin', 'admin');

-- Faculty Users (Codes mapped from image)
INSERT INTO users (email, password_hash, full_name, role) VALUES 
('mkc@college.edu', 'pass', 'Dr. Mahesh Chaubey', 'faculty'),
('npn@college.edu', 'pass', 'Mr. Nripesh Kumar', 'faculty'),
('rd@college.edu', 'pass', 'Ms. Rajni Dubey', 'faculty'),
('ak@college.edu', 'pass', 'Dr. Ajay Kumar', 'faculty'),
('vr@college.edu', 'pass', 'Dr. Vikas Rajput', 'faculty');

-- Link Users to Faculty Table (This part requires fetching User IDs, so in a real migration 
-- we'd use a script. Here is a conceptual link assuming we had the IDs. 
-- For the sake of this file being runnable, we will skip complex dynamic linking 
-- and just note that the application should handle this setup or use a procedure).

-- 4. Seed Timetable (Sample for Monday)
-- Note: In a real run, you'd need the UUIDs of subjects and classes.
-- This block is illustrative. You should look up the IDs.

-- Example: Monday
-- 10:10 - 11:05 -> DWDM (MKC)
-- 11:20 - 12:15 -> SPM (RD)
-- 12:20 - 01:15 -> DM (VR)
-- 01:20 - 02:15 -> R Prog Lab

-- To make this run successfully for the user, I will use a PL/pgSQL block to look up IDs 
-- and insert the timetable data dynamically.

DO $$
DECLARE
    class_id_val UUID;
    mkc_id UUID; npn_id UUID; rd_id UUID; rch_id UUID; 
    labwp_id UUID; labdv_id UUID; dm_id UUID; ic_id UUID;
    
    mkc_user UUID; npn_user UUID; rd_user UUID; ak_user UUID; vr_user UUID;
    
    mkc_fac UUID; npn_fac UUID; rd_fac UUID; ak_fac UUID; vr_fac UUID;
BEGIN
    -- Get Class ID
    SELECT id INTO class_id_val FROM classes WHERE name = 'BCA VI' AND section = 'Morning' LIMIT 1;
    
    -- Get Subject IDs
    SELECT id INTO mkc_id FROM subjects WHERE code = 'MKC';
    SELECT id INTO npn_id FROM subjects WHERE code = 'NPN';
    SELECT id INTO rd_id FROM subjects WHERE code = 'RD';
    SELECT id INTO rch_id FROM subjects WHERE code = 'RCH';
    SELECT id INTO labwp_id FROM subjects WHERE code = 'Lab-WP';
    SELECT id INTO labdv_id FROM subjects WHERE code = 'Lab-DV';
    SELECT id INTO dm_id FROM subjects WHERE code = 'DM';
    SELECT id INTO ic_id FROM subjects WHERE code = 'IC';

    -- Get User IDs (Assuming they were inserted in order or by email)
    SELECT id INTO mkc_user FROM users WHERE email = 'mkc@college.edu';
    SELECT id INTO npn_user FROM users WHERE email = 'npn@college.edu';
    SELECT id INTO rd_user FROM users WHERE email = 'rd@college.edu';
    SELECT id INTO ak_user FROM users WHERE email = 'ak@college.edu';
    SELECT id INTO vr_user FROM users WHERE email = 'vr@college.edu';

    -- Create Faculty Profiles and Store IDs
    INSERT INTO faculty (user_id, designation) VALUES (mkc_user, 'Professor') RETURNING id INTO mkc_fac;
    INSERT INTO faculty (user_id, designation) VALUES (npn_user, 'Assistant Professor') RETURNING id INTO npn_fac;
    INSERT INTO faculty (user_id, designation) VALUES (rd_user, 'Lecturer') RETURNING id INTO rd_fac;
    INSERT INTO faculty (user_id, designation) VALUES (ak_user, 'Lab Instructor') RETURNING id INTO ak_fac;
    INSERT INTO faculty (user_id, designation) VALUES (vr_user, 'Professor') RETURNING id INTO vr_fac;

    -- MONDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Monday', '10:10', '11:05', mkc_id, mkc_fac),
    (class_id_val, 'Monday', '11:20', '12:15', rd_id, rd_fac),
    (class_id_val, 'Monday', '12:20', '13:15', dm_id, vr_fac),
    (class_id_val, 'Monday', '13:20', '14:15', rch_id, NULL); -- Complex lab, leaving faculty NULL for now

    -- TUESDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Tuesday', '09:10', '10:05', npn_id, npn_fac),
    (class_id_val, 'Tuesday', '10:10', '11:05', labwp_id, npn_fac),
    -- BREAK
    (class_id_val, 'Tuesday', '11:20', '12:15', labdv_id, ak_fac);

    -- WEDNESDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Wednesday', '09:10', '10:05', labdv_id, ak_fac),
    (class_id_val, 'Wednesday', '10:10', '11:05', dm_id, vr_fac),
    (class_id_val, 'Wednesday', '11:20', '12:15', mkc_id, mkc_fac),
    (class_id_val, 'Wednesday', '12:20', '13:15', rd_id, rd_fac);
    
    -- THURSDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Thursday', '09:10', '10:05', npn_id, npn_fac),
    (class_id_val, 'Thursday', '10:10', '11:05', labwp_id, npn_fac),
    (class_id_val, 'Thursday', '11:20', '12:15', labdv_id, ak_fac),
    (class_id_val, 'Thursday', '12:20', '13:15', mkc_id, mkc_fac);

    -- FRIDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Friday', '09:10', '10:05', labdv_id, ak_fac),
    (class_id_val, 'Friday', '11:20', '12:15', rd_id, rd_fac),
    (class_id_val, 'Friday', '12:20', '13:15', labwp_id, npn_fac);

    -- SATURDAY
    INSERT INTO timetable (class_id, day_of_week, start_time, end_time, subject_id, faculty_id) VALUES
    (class_id_val, 'Saturday', '09:10', '10:05', npn_id, npn_fac),
    (class_id_val, 'Saturday', '10:10', '11:05', labwp_id, npn_fac);

END $$;
